language: clojure

install:
  - wget https://www.foundationdb.org/downloads/6.2.19/ubuntu/installers/foundationdb-clients_6.2.19-1_amd64.deb
  - wget https://www.foundationdb.org/downloads/6.2.19/ubuntu/installers/foundationdb-server_6.2.19-1_amd64.deb
  - sudo dpkg -i foundationdb-clients_6.2.19-1_amd64.deb foundationdb-server_6.2.19-1_amd64.deb

script:
  - make test

cache:
  directories:
  - $HOME/.m2
